version: 2.1
workflows:
  all:
    jobs:
      - lint
      - clippy
      - tests:
          matrix:
            parameters:
              rust-version: ["stable", "beta", "nightly"]

step_defs:
  - run: &rust_version
      name: Set Rust version stable
      command: |
        curl -o rustup https://sh.rustup.rs
        bash rustup -y
        . "$HOME/.cargo/env"
        rustup update << parameters.rust-version >>
        rustup default << parameters.rust-version >>
        rustup component add clippy
  - run: &build_version_stable
      name: Set Rust version
      command: |
        curl -o rustup https://sh.rustup.rs
        bash rustup -y
        . "$HOME/.cargo/env"
        rustup update stable
        rustup default stable
        rustup component add clippy

environment: &rust_env
  PHANTOM: "hello"

jobs:
  clippy:
    machine:
      image: ubuntu-2204:current
    environment: *rust_env
    steps:
      - checkout
      - run: *build_version_stable
      - run:
          name: Clippy
          command: cargo clippy
  lint:
    machine:
      image: ubuntu-2204:current
    environment: *rust_env
    steps:
      - checkout
      - run: *build_version_stable
      - run:
          name: Lint
          command: cargo fmt --all -- --check
  tests:
    machine:
      image: ubuntu-2204:current
    environment: *rust_env
    parameters:
      rust-version:
        type: string
    steps:
      - checkout
      - run: *rust_version
      - run:
          name: Build
          command: cargo build --release
      - run:
          name: Run r1cs test
          command: cargo test --release -- --nocapture
